# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

#pool:
#  vmImage: ubuntu-latest

variables:
# For ecommerce
  imageRepositoryecomm: 'ecommerce-store-app'
  containerRegistryecomm: 'Erick Container Registry'
  dockerfilePathecomm: '**/ecommerce.dockerfile'
  IMAGE_ECOMM: '$(Build.BuildId)'
# For Json Server
  imageRepositoryjsvr: 'json-server'
  containerRegistryjsvr: 'Erick Container Registry'
  dockerfilePathjsvr: '**/jserver.dockerfile'
  IMAGE_JSVR: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and run tests
    jobs:  
    - job: Build
      displayName: Building the application
      pool:
        vmImage: ubuntu-latest
      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: Docker@2
        displayName: 'Build ecommerce.dockerfile'
        inputs:
          containerRegistry: '$(containerRegistryecomm)'
          repository: '$(imageRepositoryecomm)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePathecomm)'
          tags: '$(IMAGE_ECOMM)'

      - task: Docker@2
        displayName: 'Build jserver.dockerfile'
        inputs:
          containerRegistry: '$(containerRegistryjsvr)'
          repository: '$(imageRepositoryjsvr)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePathjsvr)'
          tags: '$(IMAGE_JSVR)'

